website/allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

website/sharifa/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('website.urls', namespace='website')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^sharifaAdmin/dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^sharifaAdmin/login/$', AdminLogInView.as_view(), name='adminLogIn'),
    url(r'^sharifaAdmin/logout/$', AdminLogOutView.as_view(), name='adminLogOut'),

    url(r'^sharifaAdmin/category/list/$',
        ItemCategoryListView.as_view(), name='itemCategoryList'),
    url(r'^sharifaAdmin/category/create/$',
        ItemCategoryCreateView.as_view(), name='itemCategoryCreate'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/$',
        ItemCategoryDetailView.as_view(), name='itemCategoryDetail'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/delete$',
        ItemCategoryDeleteView.as_view(), name='itemCategoryDelete'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/update/$',
        ItemCategoryUpdateView.as_view(), name='itemCategoryUpdate'),

    url(r'^sharifaAdmin/page/list/$', PageListView.as_view(), name='pageList'),
    url(r'^sharifaAdmin/page/create/$',
        PageCreateView.as_view(), name='pageCreate'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/delete/$',
        PageDeleteView.as_view(), name='pageDelete'),

    url(r'^sharifaAdmin/product/list/$',
        ProductListView.as_view(), name='productList'),
    url(r'^sharifaAdmin/product/create/$',
        ProductCreateView.as_view(), name='productCreate'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/$',
        ProductDetailView.as_view(), name='productDetail'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/update/$',
        ProductUpdateView.as_view(), name='productUpdate'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/delete/$',
        ProductDeleteView.as_view(), name='productDelete'),
    url(r'^sharifaAdmin/product/create/(?P<pk>\d+)/$',
        ProductCreateFromQuoatationView.as_view(), name='productCreateFromQuotation'),

    url(r'^sharifaAdmin/profile/list/$',
        ProfileListView.as_view(), name='profileList'),

    url(r'^sharifaAdmin/quotation/list/$',
        QuotationListView.as_view(), name='quotationList'),
    url(r'^sharifaAdmin/quotation/create/(?P<id>\d+)/$',
        QuotationCreateView.as_view(), name='quotationCreate'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/$',
        QuotationDetailView.as_view(), name='quotationDetail'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/update/$',
        QuotationUpdateView.as_view(), name='quotationUpdate'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/delete/$',
        QuotationDeleteView.as_view(), name='quotationDelete'),

    url(r'^sharifaAdmin/requestproduct/list/$',
        RequestedProductListView.as_view(), name='requestProductList'),
    url(r'^sharifaAdmin/requestproduct/(?P<pk>\d+)/$',
        RequestedProductDetailView.as_view(), name='requestProductDetail'),
    url(r'^sharifaAdmin/requestproduct/(?P<pk>\d+)/delete/$',
        RequestedProductDeleteView.as_view(), name='requestProductDelete'),

    url(r'^sharifaAdmin/shop/list/$', ShopListView.as_view(), name='shopList'),
    url(r'^sharifaAdmin/shop/create/$',
        ShopCreateView.as_view(), name='shopCreate'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/$',
        ShopDetailView.as_view(), name='shopDetail'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/update/$',
        ShopUpdateView.as_view(), name='shopUpdate'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/delete/$',
        ShopDeleteView.as_view(), name='shopDelete'),

    url(r'^sharifaAdmin/siteconfig/list/$',
        SiteConfigListView.as_view(), name='siteConfigList'),
    url(r'^sharifaAdmin/siteconfig/create/$',
        SiteConfigCreateView.as_view(), name='siteConfigCreate'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/$',
        SiteConfigDetailView.as_view(), name='siteConfigDetail'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/update/$',
        SiteConfigUpdateView.as_view(), name='siteConfigUpdate'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/delete/$',
        SiteConfigDeleteView.as_view(), name='siteConfigDelete'),

    url(r'^sharifaAdmin/staff/list/$', StaffListView.as_view(), name='staffList'),
    url(r'^sharifaAdmin/staff/create/$',
        StaffCreateView.as_view(), name='staffCreate'),
    url(r'^sharifaAdmin/staff/(?P<pk>\d+)/email-change/$',
        StaffEmailChangeView.as_view(), name='staffEmailChange'),
    url(r'^sharifaAdmin/staff/(?P<pk>\d+)/toggle-group/$',
        StaffToggleGroupView.as_view(), name='staffToggleGroup'),

    url(r'^membership/$', MembershipListView.as_view(), name='membershipList'),
    url(r'^membership/(?P<slug>[\w-]+)/$',
        BuyMembership.as_view(), name='buyMembership'),
    url(r'^membership/activate_deactivate/(?P<pkP>\d+)/$',
        MembershipActivateDeactivateView.as_view(), name='activateDeavtivate'),
    url(r'^membership/approve_disapprove/(?P<pk>\d+)/$',
        MembershipApproveDisapproveView.as_view(), name='activateDeavtivate'),

    url(r'^profile/(?P<pk>\d+)/$', ProfileDetailView.as_view(), name='profileDetail'),
    url(r'^profile/(?P<pk>\d+)/update/$',
        ProfileUpdateView.as_view(), name='profileUpdate'),

    url(r'^requestproduct/$', UserRequestedProductCreateView.as_view(),
        name='userRequestProductCreate'),
    url(r'^quotation/(?P<pk>\d+)/$',
        UserQuotationDetailView.as_view(), name='userQuotationDetail'),
    url(r'^shops/$', UserShopListView.as_view(), name='userShopList'),
    url(r'^categories/$', UserItemCategoryListView.as_view(),
        name='userItemCategoryList'),
    url(r'^categories/(?P<slug>[\w-]+)/$',
        UserItemCategoryDetailView.as_view(), name='userItemCategoryDetail'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),

    url(r'^products/$',
        UserProductListView.as_view(), name='userProductList'),
    url(r'^products/(?P<slug>[\w-]+)/$',
        UserProductDetailView.as_view(), name='userProductDetail'),


]

website/website/views.py
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView, FormView
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.utils import timezone
from datetime import timedelta
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.utils.text import slugify
from django.db.models import Q

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import random
import string

from .models import *
from .forms import *
# # Create your views here.


class AdminLogInView(View):
    def get(self, request):
        form = LogInForm()
        context = {
            'form': form,
        }
        return render(request, 'website/adminLogIn.html', context)

    def post(self, request):
        form = LogInForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                messages.success(request, "Logged In Successfully")
                login(request, user)
                return redirect('website:dashboard')
        messages.warning(request, "Log In Failure")
        context = {
            'form': form,
        }
        return render(request, 'website/adminLogIn.html', context)


class AdminLogOutView(View):

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            logout(request)
        messages.success(request, "Logged Out Successfully")
        return redirect('website:adminLogIn')


class DashboardView(TemplateView):
    template_name = 'website/dashboard.html'


class ItemCategoryCreateView(SuccessMessageMixin, CreateView):
    model = ItemCategory
    template_name = 'website/itemCategoryCreate.html'
    form_class = ItemCategoryForm
    success_url = reverse_lazy("website:itemCategoryList")
    success_message = "Item Category Successfully Added"


class ItemCategoryUpdateView(SuccessMessageMixin, UpdateView):
    model = ItemCategory
    template_name = 'website/itemCategoryUpdate.html'
    form_class = ItemCategoryForm
    success_url = reverse_lazy("website:itemCategoryList")
    success_message = "Item Category Successfully Updated"


class ItemCategoryDetailView(DetailView):
    model = ItemCategory
    template_name = 'website/itemCategoryDetail.html'


class ItemCategoryListView(ListView):
    model = ItemCategory
    template_name = 'website/itemCategoryList.html'
    context_object_name = 'itemCategories'

    def get_queryset(self):
        return ItemCategory.objects.filter(deleted_at=None)


class ItemCategoryDeleteView(SuccessMessageMixin, DeleteView):
    model = ItemCategory
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:itemCategoryList")
    success_message = "Item Category Successfully Deleted"


class PageCreateView(SuccessMessageMixin, CreateView):
    model = Page
    template_name = 'website/pageCreate.html'
    form_class = PageForm
    success_url = reverse_lazy("website:pageList")
    success_message = "Page Successfully Added"


class PageUpdateView(SuccessMessageMixin, UpdateView):
    model = Page
    template_name = 'website/pageUpdate.html'
    form_class = PageForm
    success_url = reverse_lazy("website:pageList")
    success_message = "Page Successfully Updated"


class PageDetailView(DetailView):
    model = Page
    template_name = 'website/pageDetail.html'


class PageListView(ListView):
    model = Page
    template_name = 'website/pageList.html'
    context_object_name = 'pages'

    def get_queryset(self):
        return Page.objects.filter(deleted_at=None)


class PageDeleteView(SuccessMessageMixin, DeleteView):
    model = Page
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:pageList")
    success_message = "Page Successfully Deleted"


class ProductCreateView(SuccessMessageMixin, CreateView):
    model = Product
    template_name = 'website/productCreate.html'
    form_class = ProductForm
    success_url = reverse_lazy("website:productList")
    success_message = "Product Successfully Added"


class ProductUpdateView(SuccessMessageMixin, UpdateView):
    model = Product
    template_name = 'website/productUpdate.html'
    form_class = ProductForm
    success_url = reverse_lazy("website:productList")
    success_message = "Product Successfully Updated"


class ProductDetailView(DetailView):
    model = Product
    template_name = 'website/productDetail.html'


class ProductListView(ListView):
    model = Product
    template_name = 'website/productList.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(deleted_at=None)


class ProductDeleteView(SuccessMessageMixin, DeleteView):
    model = Product
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:productList")
    success_message = "Product Successfully Deleted"


class QuotationCreateView(SuccessMessageMixin, CreateView):
    model = Quotation
    form_class = QuotationForm
    template_name = 'website/quotationCreate.html'
    success_url = reverse_lazy("website:quotationList")
    success_message = "Quotation Successfully Added"

    def dispatch(self, request, *args, **kwargs):
        id = kwargs['id']
        self.requested_product = RequestedProduct.objects.get(pk=id)
        quotation = Quotation.objects.filter(
            requested_product=self.requested_product).first()
        if quotation:
            messages.warning(request, "Quotation Alredy Created.")
            return redirect('website:requewstProductList')
        return super(QuotationCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form, **kwargs):
        form.instance.quoted_by = self.request.user
        form.instance.requested_product = self.requested_product
        form.save()
        self.requested_product.quoted = True
        self.requested_product.save()
        return super(QuotationCreateView, self).form_valid(form, *kwargs)


class QuotationUpdateView(SuccessMessageMixin, UpdateView):
    model = Quotation
    form_class = QuotationForm
    template_name = 'website/quotationUpdate.html'
    success_url = reverse_lazy("website:quotationList")
    success_message = "Quotation Successfully Updated"


class QuotationListView(ListView):
    model = Quotation
    template_name = 'website/quotationList.html'
    context_object_name = 'quotations'

    def get_queryset(self):
        return Quotation.objects.filter(deleted_at=None)


class QuotationDetailView(DetailView):
    model = Quotation
    template_name = 'website/quotationDetail.html'


class QuotationDeleteView(SuccessMessageMixin, DeleteView):
    model = Quotation
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:quotationList")
    success_message = "Quotation Successfully Deleted"


class ProductCreateFromQuoatationView(View):
    def get(self, request, **kwars):
        quotation = get_object_or_404(Quotation, pk=kwars['pk'])
        if quotation:
            slug = slugify(quotation.requested_product.title) + \
                "-" + str(quotation.id)
            if not Product.objects.filter(slug=slug):
                product = Product()
                product.title = quotation.requested_product.title
                product.slug = slug
                product.category = quotation.category
                product.price = quotation.price
                product.approx_taxes = quotation.approx_taxes
                product.domestic_shipping = quotation.domestic_shipping
                product.height = quotation.height
                product.length = quotation.length
                product.width = quotation.width
                product.weight = quotation.weight
                product.link = quotation.requested_product.link
                product.save()
                form = ProductForm(instance=product)
            else:
                messages.error(
                    request, "Product can be created only once. Only editing is possible.")
                return redirect("website:productUpdate", slug=slug)

        context = {
            "form": form,
        }
        return render(request, "website/productCreateFromQuotation.html", context)

    def post(self, request, **kwargs):
        form = ProductForm(request.POST or None)
        if form.is_valid():
            form.save()
        return redirect("website:productList")


class RequestedProductListView(ListView):
    model = RequestedProduct
    template_name = 'website/requestProductList.html'
    context_object_name = 'requestProducts'

    def get_queryset(self):
        return RequestedProduct.objects.filter(deleted_at=None)


class RequestedProductDetailView(DetailView):
    model = RequestedProduct
    template_name = 'website/requestProductDetail.html'


class RequestedProductDeleteView(SuccessMessageMixin, DeleteView):
    model = RequestedProduct
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:requestProductList")
    success_message = "Requested Product Successfully Deleted"


class ShopCreateView(SuccessMessageMixin, CreateView):
    model = Shop
    template_name = 'website/shopCreate.html'
    form_class = ShopForm
    success_url = reverse_lazy("website:shopList")
    success_message = "Shop Successfully Added"


class ShopUpdateView(SuccessMessageMixin, UpdateView):
    model = Shop
    template_name = 'website/shopUpdate.html'
    form_class = ShopForm

website/templates/website/delete.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    Delete {{ object }}
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
    <div class="card">
        <div class="card-body">
            <form class="floating-label" action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input class="btn btn-danger" type="submit" value="Confirm" />
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

website/templates/website/itemCategoryList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Item Category List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Item Category List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'website:itemCategoryCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">Name</th>
                                    <th class="sort-alpha">Slug</th>
                                    <th class="sort-alpha" >Harmony Code</th>
                                    <th class="sort-numeric" >Popularity</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for itemCategory in itemCategories %}
                                    <tr>
                                        <td>{{itemCategory.id}}</td>
                                        <td><a href="{% url 'website:itemCategoryDetail' itemCategory.slug %}"> {{itemCategory.title}}</a></td>
                                        <td>{{itemCategory.slug}}</td>
                                        <td>{{itemCategory.harmony_code}}</td>
                                        <td>{{itemCategory.popularity}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn dropdown-toggle btn-sm" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'website:itemCategoryUpdate' itemCategory.slug %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                    <li><a href="{% url 'website:itemCategoryDelete' itemCategory.slug %}"><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#itemCategory').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}

website/templates/website/pageCreate.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    {{block.super}} | Page Create
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#page').addClass('active')
</script>
{% endblock %}

website/templates/website/pageList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Page List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Page List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'website:pageCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover"  style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">Name</th>
                                    <th class="sort-alpha">Slug</th>
                                    <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for page in pages %}
                                    <tr>
                                        <td class="sort-numeric">{{page.id}}</td>
                                        <td><a href="{% url 'website:pageDetail' page.slug %}">{{page.title}}</a></td>
                                        <td>{{page.slug}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'website:pageUpdate' page.slug %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                    <li><a href="{% url 'website:pageDelete' page.slug %}"><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#page').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}

website/templates/website/pageUpdate.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    {{block.super}} | Page Update
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Update</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#page').addClass('active')
</script>
{% endblock %}