website/allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

website/sharifa/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('website.urls', namespace='website')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^sharifaAdmin/dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^sharifaAdmin/login/$', AdminLogInView.as_view(), name='adminLogIn'),
    url(r'^sharifaAdmin/logout/$', AdminLogOutView.as_view(), name='adminLogOut'),

    url(r'^sharifaAdmin/category/list/$',
        ItemCategoryListView.as_view(), name='itemCategoryList'),
    url(r'^sharifaAdmin/category/create/$',
        ItemCategoryCreateView.as_view(), name='itemCategoryCreate'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/$',
        ItemCategoryDetailView.as_view(), name='itemCategoryDetail'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/delete$',
        ItemCategoryDeleteView.as_view(), name='itemCategoryDelete'),
    url(r'^sharifaAdmin/category/(?P<slug>[\w-]+)/update/$',
        ItemCategoryUpdateView.as_view(), name='itemCategoryUpdate'),

    url(r'^sharifaAdmin/page/list/$', PageListView.as_view(), name='pageList'),
    url(r'^sharifaAdmin/page/create/$',
        PageCreateView.as_view(), name='pageCreate'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^sharifaAdmin/page/(?P<slug>[\w-]+)/delete/$',
        PageDeleteView.as_view(), name='pageDelete'),

    url(r'^sharifaAdmin/product/list/$',
        ProductListView.as_view(), name='productList'),
    url(r'^sharifaAdmin/product/create/$',
        ProductCreateView.as_view(), name='productCreate'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/$',
        ProductDetailView.as_view(), name='productDetail'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/update/$',
        ProductUpdateView.as_view(), name='productUpdate'),
    url(r'^sharifaAdmin/product/(?P<slug>[\w-]+)/delete/$',
        ProductDeleteView.as_view(), name='productDelete'),
    url(r'^sharifaAdmin/product/create/(?P<pk>\d+)/$',
        ProductCreateFromQuoatationView.as_view(), name='productCreateFromQuotation'),

    url(r'^sharifaAdmin/profile/list/$',
        ProfileListView.as_view(), name='profileList'),

    url(r'^sharifaAdmin/quotation/list/$',
        QuotationListView.as_view(), name='quotationList'),
    url(r'^sharifaAdmin/quotation/create/(?P<id>\d+)/$',
        QuotationCreateView.as_view(), name='quotationCreate'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/$',
        QuotationDetailView.as_view(), name='quotationDetail'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/update/$',
        QuotationUpdateView.as_view(), name='quotationUpdate'),
    url(r'^sharifaAdmin/quotation/(?P<pk>\d+)/delete/$',
        QuotationDeleteView.as_view(), name='quotationDelete'),

    url(r'^sharifaAdmin/requestproduct/list/$',
        RequestedProductListView.as_view(), name='requestProductList'),
    url(r'^sharifaAdmin/requestproduct/(?P<pk>\d+)/$',
        RequestedProductDetailView.as_view(), name='requestProductDetail'),
    url(r'^sharifaAdmin/requestproduct/(?P<pk>\d+)/delete/$',
        RequestedProductDeleteView.as_view(), name='requestProductDelete'),

    url(r'^sharifaAdmin/shop/list/$', ShopListView.as_view(), name='shopList'),
    url(r'^sharifaAdmin/shop/create/$',
        ShopCreateView.as_view(), name='shopCreate'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/$',
        ShopDetailView.as_view(), name='shopDetail'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/update/$',
        ShopUpdateView.as_view(), name='shopUpdate'),
    url(r'^sharifaAdmin/shop/(?P<pk>\d+)/delete/$',
        ShopDeleteView.as_view(), name='shopDelete'),

    url(r'^sharifaAdmin/siteconfig/list/$',
        SiteConfigListView.as_view(), name='siteConfigList'),
    url(r'^sharifaAdmin/siteconfig/create/$',
        SiteConfigCreateView.as_view(), name='siteConfigCreate'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/$',
        SiteConfigDetailView.as_view(), name='siteConfigDetail'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/update/$',
        SiteConfigUpdateView.as_view(), name='siteConfigUpdate'),
    url(r'^sharifaAdmin/siteconfig/(?P<pk>\d+)/delete/$',
        SiteConfigDeleteView.as_view(), name='siteConfigDelete'),

    url(r'^sharifaAdmin/staff/list/$', StaffListView.as_view(), name='staffList'),
    url(r'^sharifaAdmin/staff/create/$',
        StaffCreateView.as_view(), name='staffCreate'),
    url(r'^sharifaAdmin/staff/(?P<pk>\d+)/email-change/$',
        StaffEmailChangeView.as_view(), name='staffEmailChange'),
    url(r'^sharifaAdmin/staff/(?P<pk>\d+)/toggle-group/$',
        StaffToggleGroupView.as_view(), name='staffToggleGroup'),

    url(r'^membership/$', MembershipListView.as_view(), name='membershipList'),
    url(r'^membership/(?P<slug>[\w-]+)/$',
        BuyMembership.as_view(), name='buyMembership'),
    url(r'^membership/activate_deactivate/(?P<pkP>\d+)/$',
        MembershipActivateDeactivateView.as_view(), name='activateDeavtivate'),
    url(r'^membership/approve_disapprove/(?P<pk>\d+)/$',
        MembershipApproveDisapproveView.as_view(), name='activateDeavtivate'),

    url(r'^profile/(?P<pk>\d+)/$', ProfileDetailView.as_view(), name='profileDetail'),
    url(r'^profile/(?P<pk>\d+)/update/$',
        ProfileUpdateView.as_view(), name='profileUpdate'),

    url(r'^requestproduct/$', UserRequestedProductCreateView.as_view(),
        name='userRequestProductCreate'),
    url(r'^quotation/(?P<pk>\d+)/$',
        UserQuotationDetailView.as_view(), name='userQuotationDetail'),
    url(r'^shops/$', UserShopListView.as_view(), name='userShopList'),
    url(r'^categories/$', UserItemCategoryListView.as_view(),
        name='userItemCategoryList'),
    url(r'^categories/(?P<slug>[\w-]+)/$',
        UserItemCategoryDetailView.as_view(), name='userItemCategoryDetail'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),

    url(r'^products/$',
        UserProductListView.as_view(), name='userProductList'),
    url(r'^products/(?P<slug>[\w-]+)/$',
        UserProductDetailView.as_view(), name='userProductDetail'),


]

website/templates/layouts/admin/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block head_title %}Sharifa Admin Pannel{% endblock %}</title>
    {% include "layouts/admin/include/head.html" %}
    {% block extra_head %}
    {% endblock %}
</head>
<body class="menubar-hoverable header-fixed full-content">
    <!-- BEGIN HEADER-->
    <header id="header" >
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand" >
                        <div class="brand-holder">
                            <a href="{% url 'website:dashboard' %}">
                                <span class="text-lg text-bold text-primary">SHARIFA ADMIN</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">
                <ul class="header-nav header-nav-options">
                    <li>
                        <!-- Search form -->
                        <form class="navbar-search" role="search">
                            <div class="form-group">
                                <input type="search" class="form-control" name="headerSearch" placeholder="Enter your keyword">
                            </div>
                            <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
                        </form>
                    </li>
                </ul><!--end .header-nav-options -->
                <ul class="header-nav header-nav-profile">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                            <img src="{% static 'assets/img/avatar1.jpg' %}" alt="" />
                            <span class="profile-info">
                                {{request.user.get_full_name}}
                                <small> Administrator</small>
                            </span>
                        </a>
                        <ul class="dropdown-menu animation-dock">
                            <li class="dropdown-header">Config</li>
                            <li><a href="#">My profile</a></li>
                            <li><a href="#">My blog <span class="badge style-danger pull-right">16</span></a></li>
                            <li><a href="#">My appointments</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'website:staffEmailChange' request.user.id %}"><i class="fa fa-fw fa-envelope"></i> Change Email</a></li>
                            <li><a href="#"  data-toggle="modal" data-target="#logOutModal"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                        </ul><!--end .dropdown-menu -->
                    </li><!--end .dropdown -->
                </ul><!--end .header-nav-profile -->
            </div><!--end #header-navbar-collapse -->
        </div>
    </header>
    <!-- END HEADER-->

    <div class="modal fade" id="logOutModal" tabindex="-1" role="dialog" aria-labelledby="logOutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="simpleModalLabel">Log Out</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to logout?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'website:adminLogOut' %}"  style="text-decoration:none;">Logout</a></button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- END SIMPLE MODAL MARKUP -->


    <!-- BEGIN BASE-->
    <div id="base">
        {% if messages %}
        {% for message in messages %}
        <div id="toast-container" class="toast-bottom-right" aria-live="polite" role="alert">
           <div class="toast toast-{{message.tags}}">
               <div class="toast-message">{{ message }}</div>
           </div>
       </div>
       {% endfor %}
       {% endif %}
       <!-- BEGIN CONTENT-->
       <div id="content">
        {% block content %}
        {% endblock %}
    </div><!--end #content-->
    <!-- END CONTENT -->
    {% block menubar%}
    <!-- BEGIN MENUBAR-->
    <div id="menubar" class="menubar-inverse ">
        <div class="menubar-fixed-panel">
            <div>
                <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <div class="expanded">
                <a href="{% url 'website:dashboard' %}">
                    <span class="text-lg text-bold text-primary ">SHARIFA&nbsp;ADMIN</span>
                </a>
            </div>
        </div>
        <div class="menubar-scroll-panel">

            <!-- BEGIN MAIN MENU -->
            <ul id="main-menu" class="gui-controls">

                <!-- BEGIN DASHBOARD -->
                <li>
                    <a href="{% url 'website:dashboard' %}" id="dashboard">
                        <div class="gui-icon"><i class="fa fa-home"></i></div>
                        <span class="title">Dashboard</span>
                    </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->

                <li>
                    <a href="{% url 'website:itemCategoryList' %}" id="itemCategory">
                        <div class="gui-icon"><i class="fa fa-th-list"></i></div>
                        <span class="title">Item Category</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:pageList' %}" id="page">
                        <div class="gui-icon"><i class="md md-web"></i></div>
                        <span class="title">Page</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:productList' %}" id="product">
                        <div class="gui-icon"><i class="fa fa-barcode"></i></div>
                        <span class="title">Product</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:quotationList' %}" id="quotation">
                        <div class="gui-icon"><i class="md md-assignment"></i></div>
                        <span class="title">Quotation</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:requestProductList' %}" id="requestProduct">
                        <div class="gui-icon"><i class="fa fa-calendar"></i></div>
                        <span class="title">Requested Products</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:shopList' %}" id="shop">
                        <div class="gui-icon"><i class="md md-shopping-cart"></i></div>
                        <span class="title">Shop</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:siteConfigList' %}" id="siteConfig">
                        <div class="gui-icon"><i class="fa fa-gears"></i></div>
                        <span class="title">Site Config</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:staffList' %}" id="staff">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">Staff</span>
                    </a>
                </li><!--end /menu-li -->

                <li>
                    <a href="{% url 'website:profileList' %}" id="user">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">User</span>
                    </a>
                </li><!--end /menu-li -->


            </ul><!--end .main-menu -->
            <!-- END MAIN MENU -->

            <div class="menubar-foot-panel">
                <small class="no-linebreak hidden-folded">
                    <span class="opacity-75">Copyright &copy; 2016</span> <strong>Prixa</strong>
                </small>
            </div>
        </div><!--end .menubar-scroll-panel-->
    </div><!--end #menubar-->
    <!-- END MENUBAR -->
    {% endblock menubar %}
    </div><!--end #base-->
<!-- END BASE -->

    {% include "layouts/admin/include/javascript.html" %}
    <script type="text/javascript">
        $(function(){
            {% if messages %}
            toastr.clear();
            {% for message in messages %}
            toastr.options.closeButton = true;
            toastr.options.progressBar = true;
            toastr.options.debug = false;
            toastr.options.positionClass = 'toast-bottom-right';
            toastr.options.showDuration = 333;
            toastr.options.hideDuration = 333;
            toastr.options.timeOut = 4000;
            toastr.options.extendedTimeOut = 4000;
            toastr.options.showEasing = 'swing';
            toastr.options.hideEasing = 'swing';
            toastr.options.showMethod = 'slideDown';
            toastr.options.hideMethod = 'slideUp';
            toastr.{{message.tags}}('{{message}}', '');
            {% endfor %}
            {% endif %}
        });

    </script>
    {% block extra_js %}
    {% endblock extra_js %}
</body>
</html>